name: Update Gist

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update Gist
        env:
          GIST_TOKEN: ${{ secrets.PACKETTOKEN }}
          GITHUB_TOKEN: ${{ secrets.SOURCE_TOKEN }}   # <-- добавили
        run: python update_gist.py
