name: Update Gist
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Process configs
        run: |
          # Получаем данные
          curl -k -H "Authorization: token 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" \
               -L "https://raw.githubusercontent.com/Roadlux/PacketVPN1.5.3-NEW/main/configInfo" \
               | jq -r '.configs[].config.stringServer' | base64 > sub.txt

      - name: Update Gist
        uses: exuanbo/actions-gist@v1
        with:
          token: ${{ secrets.PACKETTOKEN }} # Нужно создать в Secrets
          gist_id: 5d53a0965ad16d964c5fb366e11532ff # Вставьте ваш ID
          file_path: sub.txt
